odom_frame: "odom"
robot_state_topic: "/state_estimator/alma_state"
twist_command_topic: "/twist_mux/twist"
obstacle_aabb_topics:
  - "/depth_camera_front_upper/aligned_depth_to_infra1/bboxes"
  - "/depth_camera_rear_upper/aligned_depth_to_infra1/bboxes"
  - "/depth_camera_left/aligned_depth_to_infra1/bboxes"
  - "/depth_camera_right/aligned_depth_to_infra1/bboxes"
goal_tf_frame: "waverider_target_frame"
ground_plane_tf_frame: "footprint"
tf_lookup_delay: { seconds: 0.02 }
occupancy_threshold: 0.1
control_period: { seconds: 0.02 }
integrator_step_size: { seconds: 0.005 }
publish_debug_visuals_every_n_iterations: 20
ground_plane_offset: { meters: 0.10 }
goal_policy:
  alpha: 25.0
  beta: 35.0
  c: 0.2
  a: 20.0
yaw_policy:
  alpha: 15.0
  beta: 20.0
  c: 0.1
  a: 20.0
  angle_forward: { degrees: 0.0 }
  track_yaw_goal: true # if false the yaw goal is dynamically adjusted to have the robot facing the goal
map_obstacles_policy:
  c: 0.1
  eta_rep: 30.0
  eta_damp: 340.0
  enable_damper: true
  enable_repulsor: true
aabb_obstacles_policy:
  r: 160.0         # overall activation strenght
  eta_rep: 500.0   # linear repulsion term
  eta_damp: 300.0  # damping -> based on robot velocity to obstacle
  enable_damper: true
  enable_repulsor: true
goal_policy_marker_scale: 0.1
yaw_policy_marker_scale: 0.1
map_obstacles_policy_marker_scale: 0.1
aabb_obstacles_policy_marker_scale: 0.1
